<a href="https://colab.research.google.com/github/GuptaShivam007/Applied_Gradient_Descent_manually_for_Neural_Network/blob/main/Applied_gradient_descent_manually.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import tensorflow as tf
from tensorflow import keras

In [4]:
dataset=pd.read_csv('insurance_data.csv')

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X_train,X_test,y_train,y_test=train_test_split(dataset[['age','affordibility']],dataset['bought_insurance'],test_size=0.2,random_state=2)

In [7]:
X_train_scaled=X_train.copy()
X_train_scaled['age']=X_train_scaled['age']/100

X_test_scaled=X_test.copy()
X_test_scaled['age']=X_test_scaled['age']/100

In [8]:
X_train_scaled


age  affordibility
16  0.25              0
6   0.55              0
3   0.52              0
21  0.26              0
26  0.23              1
25  0.54              1
12  0.27              0
4   0.46              1
10  0.18              1
5   0.56              1
20  0.21              1
2   0.47              1
7   0.60              0
24  0.50              1
23  0.45              1
18  0.19              0
11  0.28              1
22  0.40              1
27  0.46              1
13  0.29              0
15  0.55              1
8   0.62              1

In [33]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.fit(X_train_scaled,y_train,epochs=5000)

Streaming output truncated to the last 5000 lines.
1/1 [==============================] - 0s 12ms/step - loss: 0.6465 - accuracy: 0.6818
Epoch 2502/5000
1/1 [==============================] - 0s 17ms/step - loss: 0.6465 - accuracy: 0.6818
Epoch 2503/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.6464 - accuracy: 0.6818
Epoch 2504/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.6463 - accuracy: 0.6818
Epoch 2505/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.6463 - accuracy: 0.6818
Epoch 2506/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.6462 - accuracy: 0.6818
Epoch 2507/5000
1/1 [==============================] - 0s 13ms/step - loss: 0.6461 - accuracy: 0.6818
Epoch 2508/5000
1/1 [==============================] - 0s 11ms/step - loss: 0.6461 - accuracy: 0.6818
Epoch 2509/5000
1/1 [==============================] - 0s 12ms/step - loss: 0.6460 - accuracy: 0.6818
Epoch 2510/5000
1/1 [==========================

In [10]:
model.evaluate(X_test_scaled,y_test)

1/1 [==============================] - 1s 606ms/step - loss: 0.3672 - accuracy: 1.0000


[0.36724647879600525, 1.0]

In [11]:
y_pred=model.predict(X_test_scaled)
y_pred[:5]

1/1 [==============================] - 0s 130ms/step


array([[0.17078605],
       [0.4627754 ],
       [0.7061479 ],
       [0.79128915],
       [0.4252732 ]], dtype=float32)

In [12]:
y_test[:5]

1     0
0     0
14    1
9     1
19    0
Name: bought_insurance, dtype: int64

In [34]:
coef,intercept=model.get_weights()
coef,intercept

(array([[2.433204 ],
        [1.3017929]], dtype=float32),
 array([-1.7693152], dtype=float32))

In [14]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [35]:
def log_loss(y_true,y_pred):
  epsilon=1e-15
  y_pred_new=[max(i,epsilon) for i in y_pred]
  y_pred_new=[min(i,1-epsilon) for i in y_pred_new]
  y_pred_new=np.array(y_pred_new)
  return -np.mean(y_true*np.log(y_pred_new)+(1-y_true)*np.log(1-y_pred_new))

In [39]:
def gradient_descent(age,affordibility,y_true,epochs,threshold):
  w1=1
  w2=1
  bias=0
  rate=0.01
  n=len(age)
  for i in range(epochs):
    weight=w1*age+w2*affordibility+bias
    y_pred=sigmoid(weight)
    loss=log_loss(y_true,y_pred)
    w1d=(1/n)*np.dot(np.transpose(age),(y_pred-y_true))
    w2d=(1/n)*np.dot(np.transpose(affordibility),(y_pred-y_true))
    bias_d=np.mean(y_pred-y_true)
    w1=w1-rate*w1d
    w2=w2-rate*w2d
    bias=bias-rate*bias_d
    print(f'epochs:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
    if(loss<=threshold):
      break
  return w1,w2,bias

In [40]:
gradient_descent(X_train_scaled['age'],X_train_scaled['affordibility'],y_train,5000,0.5384)

epochs:0, w1:0.9994678382975036, w2:0.9989695811010494, bias:-0.002266873040895484, loss:0.714610156590683
epochs:1, w1:0.9989379169444254, w2:0.9979426703429564, bias:-0.004528085878850044, loss:0.7139626709959125
epochs:2, w1:0.9984102332684484, w2:0.9969192651214376, bias:-0.006783645822548399, loss:0.7133187045766203
epochs:3, w1:0.9978847845730439, w2:0.9958993627812593, bias:-0.009033560237709988, loss:0.7126782433466569
epochs:4, w1:0.9973615681376456, w2:0.9948829606165135, bias:-0.011277836546642987, loss:0.7120412733152942
epochs:5, w1:0.9968405812178255, w2:0.993870055870895, bias:-0.013516482227797118, loss:0.7114077804879038
epochs:6, w1:0.996321821045469, w2:0.9928606457379827, bias:-0.015749504815315295, loss:0.7107777508666269
epochs:7, w1:0.9958052848289519, w2:0.9918547273615201, bias:-0.01797691189858417, loss:0.710151170451044
epochs:8, w1:0.9952909697533174, w2:0.9908522978357003, bias:-0.020198711121783612, loss:0.7095280252388384
epochs:9, w1:0.9947788729804532, 

(2.065823006462115, 1.3074088874978609, -1.6144065599634236)

In [41]:
coef,intercept

(array([[2.433204 ],
        [1.3017929]], dtype=float32),
 array([-1.7693152], dtype=float32))